name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu-20.04, macos-latest]
        exclude:
           - os: macos-latest
             compiler: gcc
    env:
      CC: ${{ matrix.compiler }}
      CMAKE_GENERATOR: Ninja

    steps:
    - uses: actions/checkout@v3

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: re
        repo: https://github.com/baresip/re
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: openssl path macos
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl" >> $GITHUB_ENV
    
    - name: install packages
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update && sudo apt-get install -y ninja-build

    - name: make re/rem
      shell: bash
      run: |
        cd ..
        for p in re rem; do
          cmake -S $p -B $p/build
          cmake --build $p/build -j
        done

    - name: retest
      run: |
        cd ../retest && make && ./retest -r
