name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu-20.04, macos-latest]
        exclude:
           - os: macos-latest
             compiler: gcc
    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v3

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: re
        repo: https://github.com/baresip/re
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: openssl path macos
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl" >> $GITHUB_ENV

    - name: retest
      run: |
        cd ..
        make -C re libre.a
        cmake -S rem -B rem/build && cmake --build rem/build
        cd retest && cmake . && make && ./retest -r
