name: ccheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ccheck
      run: |
        wget "https://raw.githubusercontent.com/baresip/baresip/stable/test/ccheck.py"
        python3 ccheck.py
